class UsageStardust {
  final String date, poster, title, category, balance;
  final int usageId;

  UsageStardust({
    required this.date,
    required this.poster,
    required this.title,
    required this.category,
    required this.balance,
    required this.usageId,
  });
}

List<UsageStardust> usageStardusts = [
  UsageStardust(
    date: "2022.11.29",
    poster: "assets/images/img_rep_redVelvet.png",
    title: "Vote on Red Velvet",
    category: "Voted",
    balance: "15000",
    usageId: 0,
  ),
  UsageStardust(
    date: "2022.11.29",
    poster: "assets/images/img_rep_redVelvet.png",
    title: "Vote on Red Velvet",
    category: "Voted",
    balance: "15000",
    usageId: 1,
  ),
  UsageStardust(
    date: "2022.11.29",
    poster: "assets/images/img_rep_redVelvet.png",
    title: "Vote on Red Velvet",
    category: "Voted",
    balance: "15000",
    usageId: 2,
  ),
  UsageStardust(
    date: "2022.11.29",
    poster: "assets/images/img_rep_redVelvet.png",
    title: "Vote on Red Velvet",
    category: "Voted",
    balance: "15000",
    usageId: 3,
  ),
  UsageStardust(
    date: "2022.11.29",
    poster: "assets/images/img_rep_redVelvet.png",
    title: "Vote on Red Velvet",
    category: "Voted",
    balance: "15000",
    usageId: 4,
  ),
  UsageStardust(
    date: "2022.11.29",
    poster: "assets/images/img_rep_redVelvet.png",
    title: "Vote on Red Velvet",
    category: "Voted",
    balance: "15000",
    usageId: 5,
  ),
  UsageStardust(
    date: "2022.11.29",
    poster: "assets/images/img_rep_redVelvet.png",
    title: "Vote on Red Velvet",
    category: "Voted",
    balance: "15000",
    usageId: 6,
  ),
  UsageStardust(
    date: "2022.11.29",
    poster: "assets/images/img_rep_redVelvet.png",
    title: "Vote on Red Velvet",
    category: "Voted",
    balance: "15000",
    usageId: 7,
  ),
  UsageStardust(
    date: "2022.11.29",
    poster: "assets/images/img_rep_redVelvet.png",
    title: "Vote on Red Velvet",
    category: "Voted",
    balance: "15000",
    usageId: 8,
  ),
  UsageStardust(
    date: "2022.11.29",
    poster: "assets/images/img_rep_redVelvet.png",
    title: "Vote on Red Velvet",
    category: "Voted",
    balance: "15000",
    usageId: 9,
  ),
  UsageStardust(
    date: "2022.11.29",
    poster: "assets/images/img_rep_redVelvet.png",
    title: "Vote on Red Velvet",
    category: "Voted",
    balance: "15000",
    usageId: 10,
  ),
  UsageStardust(
    date: "2022.11.29",
    poster: "assets/images/img_rep_redVelvet.png",
    title: "Vote on Red Velvet",
    category: "Voted",
    balance: "15000",
    usageId: 11,
  ),
  UsageStardust(
    date: "2022.11.29",
    poster: "assets/images/img_rep_redVelvet.png",
    title: "Vote on Red Velvet",
    category: "Voted",
    balance: "15000",
    usageId: 12,
  ),
  UsageStardust(
    date: "2022.11.29",
    poster: "assets/images/img_rep_redVelvet.png",
    title: "Vote on Red Velvet",
    category: "Voted",
    balance: "15000",
    usageId: 13,
  ),
];
