// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlxoSjp9NlQkpCIqDGupp0cG1Z7tdV4ZI',
    appId: '1:100693302795:web:bba1278baeca250f3af10e',
    messagingSenderId: '100693302795',
    projectId: 'starlight-clone',
    authDomain: 'starlight-clone.firebaseapp.com',
    storageBucket: 'starlight-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUUpKjZpIuSKzG2LuWs9sZ31cfMRNzxXY',
    appId: '1:100693302795:android:2d558be1c063f6283af10e',
    messagingSenderId: '100693302795',
    projectId: 'starlight-clone',
    storageBucket: 'starlight-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAWhD_Zpkru_wdtjvJBqPMFtQf0QIQojc',
    appId: '1:100693302795:ios:66b2f1f516aa92e03af10e',
    messagingSenderId: '100693302795',
    projectId: 'starlight-clone',
    storageBucket: 'starlight-clone.appspot.com',
    iosClientId:
        '100693302795-mrhcbur7hbg7bgjm4lmhnf6laidpauot.apps.googleusercontent.com',
    iosBundleId: 'com.example.starlightClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAWhD_Zpkru_wdtjvJBqPMFtQf0QIQojc',
    appId: '1:100693302795:ios:66b2f1f516aa92e03af10e',
    messagingSenderId: '100693302795',
    projectId: 'starlight-clone',
    storageBucket: 'starlight-clone.appspot.com',
    iosClientId:
        '100693302795-mrhcbur7hbg7bgjm4lmhnf6laidpauot.apps.googleusercontent.com',
    iosBundleId: 'com.example.starlightClone',
  );
}
